@file:OptIn(ExperimentalForeignApi::class)

package com.cws.kanvas.vk

import kotlinx.cinterop.ExperimentalForeignApi
import vulkan.*

fun VK_RESULT.assert(): VK_RESULT {
    if (this != VK_RESULT_SUCCESS) {
        error("Failed VK call with result - $this")
    }
    return this
}

typealias VK_RESULT = Int

const val VK_RESULT_SUCCESS = VK_SUCCESS
const val VK_RESULT_NOT_READY = VK_NOT_READY
const val VK_RESULT_TIMEOUT = VK_TIMEOUT
const val VK_RESULT_EVENT_SET = VK_EVENT_SET
const val VK_RESULT_EVENT_RESET = VK_EVENT_RESET
const val VK_RESULT_INCOMPLETE = VK_INCOMPLETE
const val VK_RESULT_ERROR_OUT_OF_HOST_MEMORY = VK_ERROR_OUT_OF_HOST_MEMORY
const val VK_RESULT_ERROR_OUT_OF_DEVICE_MEMORY = VK_ERROR_OUT_OF_DEVICE_MEMORY
const val VK_RESULT_ERROR_INITIALIZATION_FAILED = VK_ERROR_INITIALIZATION_FAILED
const val VK_RESULT_ERROR_DEVICE_LOST = VK_ERROR_DEVICE_LOST
const val VK_RESULT_ERROR_MEMORY_MAP_FAILED = VK_ERROR_MEMORY_MAP_FAILED
const val VK_RESULT_ERROR_LAYER_NOT_PRESENT = VK_ERROR_LAYER_NOT_PRESENT
const val VK_RESULT_ERROR_EXTENSION_NOT_PRESENT = VK_ERROR_EXTENSION_NOT_PRESENT
const val VK_RESULT_ERROR_FEATURE_NOT_PRESENT = VK_ERROR_FEATURE_NOT_PRESENT
const val VK_RESULT_ERROR_INCOMPATIBLE_DRIVER = VK_ERROR_INCOMPATIBLE_DRIVER
const val VK_RESULT_ERROR_TOO_MANY_OBJECTS = VK_ERROR_TOO_MANY_OBJECTS
const val VK_RESULT_ERROR_FORMAT_NOT_SUPPORTED = VK_ERROR_FORMAT_NOT_SUPPORTED
const val VK_RESULT_ERROR_FRAGMENTED_POOL = VK_ERROR_FRAGMENTED_POOL
const val VK_RESULT_ERROR_OUT_OF_POOL_MEMORY = VK_ERROR_OUT_OF_POOL_MEMORY
const val VK_RESULT_ERROR_INVALID_EXTERNAL_HANDLE = VK_ERROR_INVALID_EXTERNAL_HANDLE
const val VK_RESULT_ERROR_SURFACE_LOST_KHR = VK_ERROR_SURFACE_LOST_KHR
const val VK_RESULT_ERROR_NATIVE_WINDOW_IN_USE_KHR = VK_ERROR_NATIVE_WINDOW_IN_USE_KHR
const val VK_RESULT_SUBOPTIMAL_KHR = VK_SUBOPTIMAL_KHR
const val VK_RESULT_ERROR_OUT_OF_DATE_KHR = VK_ERROR_OUT_OF_DATE_KHR
const val VK_RESULT_ERROR_INCOMPATIBLE_DISPLAY_KHR = VK_ERROR_INCOMPATIBLE_DISPLAY_KHR
const val VK_RESULT_ERROR_VALIDATION_FAILED_EXT = VK_ERROR_VALIDATION_FAILED_EXT
const val VK_RESULT_ERROR_INVALID_SHADER_NV = VK_ERROR_INVALID_SHADER_NV
const val VK_RESULT_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT = VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT
const val VK_RESULT_ERROR_FRAGMENTATION_EXT = VK_ERROR_FRAGMENTATION_EXT
const val VK_RESULT_ERROR_NOT_PERMITTED_EXT = VK_ERROR_NOT_PERMITTED_EXT
const val VK_RESULT_ERROR_INVALID_DEVICE_ADDRESS_EXT = VK_ERROR_INVALID_DEVICE_ADDRESS_EXT
const val VK_RESULT_ERROR_OUT_OF_POOL_MEMORY_KHR = VK_ERROR_OUT_OF_POOL_MEMORY_KHR
const val VK_RESULT_ERROR_INVALID_EXTERNAL_HANDLE_KHR = VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR