package com.cws.kanvas.vk

typealias VK_RESULT = Int

const val VK_RESULT_SUCCESS = 0
const val VK_RESULT_NOT_READY = 1
const val VK_RESULT_TIMEOUT = 2
const val VK_RESULT_EVENT_SET = 3
const val VK_RESULT_EVENT_RESET = 4
const val VK_RESULT_INCOMPLETE = 5
const val VK_RESULT_ERROR_OUT_OF_HOST_MEMORY = -1
const val VK_RESULT_ERROR_OUT_OF_DEVICE_MEMORY = -2
const val VK_RESULT_ERROR_INITIALIZATION_FAILED = -3
const val VK_RESULT_ERROR_DEVICE_LOST = -4
const val VK_RESULT_ERROR_MEMORY_MAP_FAILED = -5
const val VK_RESULT_ERROR_LAYER_NOT_PRESENT = -6
const val VK_RESULT_ERROR_EXTENSION_NOT_PRESENT = -7
const val VK_RESULT_ERROR_FEATURE_NOT_PRESENT = -8
const val VK_RESULT_ERROR_INCOMPATIBLE_DRIVER = -9
const val VK_RESULT_ERROR_TOO_MANY_OBJECTS = -10
const val VK_RESULT_ERROR_FORMAT_NOT_SUPPORTED = -11
const val VK_RESULT_ERROR_FRAGMENTED_POOL = -12
const val VK_RESULT_ERROR_OUT_OF_POOL_MEMORY = -1000069000
const val VK_RESULT_ERROR_INVALID_EXTERNAL_HANDLE = -1000072003
const val VK_RESULT_ERROR_SURFACE_LOST_KHR = -1000000000
const val VK_RESULT_ERROR_NATIVE_WINDOW_IN_USE_KHR = -1000000001
const val VK_RESULT_SUBOPTIMAL_KHR = 1000001003
const val VK_RESULT_ERROR_OUT_OF_DATE_KHR = -1000001004
const val VK_RESULT_ERROR_INCOMPATIBLE_DISPLAY_KHR = -1000003001
const val VK_RESULT_ERROR_VALIDATION_FAILED_EXT = -1000011001
const val VK_RESULT_ERROR_INVALID_SHADER_NV = -1000012000
const val VK_RESULT_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT = -1000158000
const val VK_RESULT_ERROR_FRAGMENTATION_EXT = -1000161000
const val VK_RESULT_ERROR_NOT_PERMITTED_EXT = -1000174001
const val VK_RESULT_ERROR_INVALID_DEVICE_ADDRESS_EXT = -1000244000
const val VK_RESULT_ERROR_OUT_OF_POOL_MEMORY_KHR = -1000069000
const val VK_RESULT_ERROR_INVALID_EXTERNAL_HANDLE_KHR = -1000072003